"use client";
import{useState}from"react";import{createAcademicDecision,type AcademicDecision}from"@/domain/decision";
const INITIAL:AcademicDecision[]=[
 createAcademicDecision({id:"D12",documentId:"demo",revision:4,kind:"interpretation",title:"Ne koristiti riječ „dokazuje” bez dodatne potpore",rationale:"EvidenceBasis za v3 podupire oprezniju formulaciju, ne snažniji zaključak.",createdBy:"student",createdAt:"2026-09-28T12:00:00Z",affects:[{type:"claim",id:"claim-014"},{type:"source",id:"lindblom-1959"}]}),
 createAcademicDecision({id:"D11",documentId:"demo",revision:5,kind:"methodology",title:"Ne tretirati RESULT-031 kao rezultat DATASET-005",rationale:"Promijenjeni dataset zahtijeva ponovno izvođenje ili novu potvrdu analize.",createdBy:"student",createdAt:"2026-09-28T12:05:00Z",affects:[{type:"artifact",id:"dataset-005"},{type:"artifact",id:"result-031"}]})
];
export default function DecisionLogDemo(){const[items,setItems]=useState(INITIAL);const[open,setOpen]=useState(false);
 function add(){const next=createAcademicDecision({id:`D${13+items.length-2}`,documentId:"demo",revision:6,kind:"research",title:"Zadržati inkrementalistički okvir uz eksplicitno ograničenje",rationale:"Okvir je koristan za postupne prilagodbe, ali slabije objašnjava kvalitativne zaokrete.",createdBy:"student",createdAt:new Date().toISOString(),affects:[{type:"section",id:"theory"},{type:"section",id:"discussion"}]});setItems(x=>[next,...x]);setOpen(false)}
 return <section className="decision-demo"><div className="row" style={{justifyContent:"space-between"}}><h2 style={{fontSize:"1.1rem",margin:0}}>Academic Decision Log</h2><button className="btn" onClick={()=>setOpen(!open)}>Dodaj važnu odluku</button></div><p className="hint">Bilježe se namjerne akademske odluke, ne tipkanje ni svaka izmjena.</p>{open?<div className="card"><p><b>Odluka:</b> Zadržati inkrementalistički okvir uz eksplicitno ograničenje.</p><p className="hint"><b>Razlog:</b> okvir je koristan za postupne prilagodbe, ali slabije objašnjava kvalitativne zaokrete.</p><button className="btn btn-primary" onClick={add}>Spremi odluku</button></div>:null}{items.map(d=><div className="card" key={d.id}><strong>{d.id} · {d.kind}</strong><p>{d.title}</p><p className="hint">{d.rationale}</p><div className="row">{d.affects.map(a=><span className="protected-pill" key={a.type+a.id}>{a.type}:{a.id}</span>)}</div></div>)}</section>}
