"use client";
import{useMemo,useState}from"react";
import{buildMentorQueue,groupMentorQueue,type MentorProjectInput,type WaitingOn}from"@/domain/mentor-command";
import{applyReviewAction,buildCoverageMap,buildMentorReviewDelta,createReviewQueue,currentReviewItem,type ObjectChange,type ReviewCoverageRecord,type ReviewQueueItem,type ReviewQueueState}from"@/domain/mentor-review";
import{traceAcademicPaths,type AcademicGraph}from"@/domain/academic-graph";
import{evaluateAcademicReadiness}from"@/domain/readiness";

const INPUTS:MentorProjectInput[]=[
 {projectId:"p-daniel",studentId:"s-daniel",studentLabel:"Daniel Rišavi",workLabel:"Diplomski rad",lastActivityAt:"2026-09-29T10:41:00Z",reviewDeltaCount:6,studentResponseCount:2,neverReviewedCount:1,readinessBlockerCount:1,forensicAnomalyCount:0,finalReviewRequested:false,studentWorkPending:false},
 {projectId:"p-ana",studentId:"s-ana",studentLabel:"Ana Horvat",workLabel:"Završni rad",lastActivityAt:"2026-09-28T16:12:00Z",reviewDeltaCount:0,studentResponseCount:0,neverReviewedCount:0,readinessBlockerCount:0,forensicAnomalyCount:0,finalReviewRequested:false,studentWorkPending:true},
 {projectId:"p-marko",studentId:"s-marko",studentLabel:"Marko Marić",workLabel:"Diplomski rad",lastActivityAt:"2026-09-27T12:05:00Z",reviewDeltaCount:0,studentResponseCount:0,neverReviewedCount:0,readinessBlockerCount:0,forensicAnomalyCount:0,finalReviewRequested:false,studentWorkPending:false},
 {projectId:"p-petra",studentId:"s-petra",studentLabel:"Petra Novak",workLabel:"Diplomski rad",lastActivityAt:"2026-09-29T08:10:00Z",reviewDeltaCount:0,studentResponseCount:0,neverReviewedCount:0,readinessBlockerCount:2,forensicAnomalyCount:1,finalReviewRequested:true,studentWorkPending:false},
];
const DANIEL_GRAPH:AcademicGraph={objects:[{id:"CLAIM-014",type:"claim",label:"CLAIM-014 · tvrdnja o povezanosti",revision:4},{id:"S5.2",type:"section",label:"Rasprava §5.2",revision:4},{id:"K6",type:"conclusion",label:"Zaključak §6",revision:2},{id:"RESULT-031",type:"result",label:"RESULT-031 · statistički rezultat",revision:5},{id:"SOURCE-024",type:"source",label:"SOURCE-024 · novi izvor",revision:1},{id:"H2",type:"hypothesis",label:"H2 · interpretacija hipoteze",revision:3}],links:[]};
const DANIEL_REVIEWS:ReviewCoverageRecord[]=[{id:"r1",reviewerId:"mentor",objectId:"CLAIM-014",reviewedRevision:3,reviewedAt:"2026-09-20T10:00:00Z",status:"accepted"},{id:"r2",reviewerId:"mentor",objectId:"S5.2",reviewedRevision:3,reviewedAt:"2026-09-20T10:05:00Z",status:"reviewed"},{id:"r3",reviewerId:"mentor",objectId:"RESULT-031",reviewedRevision:4,reviewedAt:"2026-09-20T10:10:00Z",status:"reviewed"},{id:"r4",reviewerId:"mentor",objectId:"H2",reviewedRevision:2,reviewedAt:"2026-09-20T10:15:00Z",status:"reviewed"}];
const DANIEL_CHANGES:ObjectChange[]=[{objectId:"CLAIM-014",revision:4,kind:"content"},{objectId:"S5.2",revision:4,kind:"evidence"},{objectId:"K6",revision:2,kind:"structure"},{objectId:"RESULT-031",revision:5,kind:"analysis"},{objectId:"SOURCE-024",revision:1,kind:"evidence"},{objectId:"H2",revision:3,kind:"content"}];
type View="all"|WaitingOn;
const LABEL:Record<View,string>={all:"Svi",mentor:"Treba moju pažnju",student:"Čeka studenta",none:"Bez otvorene akcije"};
const REASON:Record<string,string>={"review-delta":"akademski relevantne promjene","student-responses":"odgovori na dorade","never-reviewed":"nikad pregledani objekti","readiness-blockers":"blokeri za predaju","forensic-anomalies":"anomalije integriteta/procesa za tehnički pregled","final-review-requested":"zatražen završni pregled"};

function ReviewQueuePanel({state,note,setNote,setState}:{state:ReviewQueueState|null;note:string;setNote:(v:string)=>void;setState:(v:ReviewQueueState|null)=>void}){
 if(!state)return null;const item=currentReviewItem(state);if(!item)return <div><h4>Pregled dovršen</h4><p>Obrađeno je {state.audits.length} audit događaja; coverage zapisa: {state.coverage.length}.</p></div>;
 const act=(action:"reviewed"|"revision-requested"|"commented"|"skipped")=>{const n=state.audits.length+1;setState(applyReviewAction(state,{reviewerId:"mentor",action,occurredAt:`2026-09-29T12:${String(n).padStart(2,"0")}:00Z`,auditId:`demo-audit-${n}`,coverageId:action==="reviewed"?`demo-coverage-${n}`:undefined,note:note||undefined}));setNote("");};
 return <div aria-label="Mentor Review Queue"><p className="hint">Stavka {state.cursor+1}/{state.items.length}</p><h4>{item.object.label}</h4><p>{item.contextLabel} · revizija {item.object.revision} · razlog: {item.reason==="changed"?"promijenjeno nakon pregleda":"novo za pregled"}</p><textarea aria-label="Mentorska bilješka" value={note} onChange={e=>setNote(e.target.value)} placeholder="Bilješka ili razlog dorade"/><div className="row"><button className="btn btn-primary" onClick={()=>act("reviewed")}>Označi pregledano</button><button className="btn" disabled={!note.trim()} onClick={()=>act("revision-requested")}>Traži doradu</button><button className="btn" disabled={!note.trim()} onClick={()=>act("commented")}>Komentiraj</button><button className="btn" onClick={()=>act("skipped")}>Preskoči</button></div><p className="hint">Audit događaji: {state.audits.length} · novi coverage zapisi: {state.coverage.length}</p></div>;
}

export default function MentorCommandCenterDemo(){
 const[view,setView]=useState<View>("mentor");const[selected,setSelected]=useState<string|null>(null);const[details,setDetails]=useState<"summary"|"review"|"revisions"|"arguments"|"checks"|"queue">("summary");const[language,setLanguage]=useState(false);const[note,setNote]=useState("");const[reviewQueue,setReviewQueue]=useState<ReviewQueueState|null>(null);
 const queue=useMemo(()=>buildMentorQueue(INPUTS),[]);const groups=useMemo(()=>groupMentorQueue(queue),[queue]);
 const shown=view==="all"?queue:groups[view];const project=queue.find(x=>x.projectId===selected)??null;
 const danielCoverage=useMemo(()=>buildCoverageMap(DANIEL_GRAPH,DANIEL_REVIEWS,"mentor"),[]);
 const danielDelta=useMemo(()=>buildMentorReviewDelta(DANIEL_GRAPH,DANIEL_REVIEWS,"mentor",DANIEL_CHANGES,{includeLanguageOnly:language}),[language]);
 const argumentPath=useMemo(()=>traceAcademicPaths({objects:[...DANIEL_GRAPH.objects,{id:"DATASET-004",type:"dataset",label:"DATASET-004 · N=238",revision:4},{id:"ANALYSIS-011",type:"analysis",label:"ANALYSIS-011 · regresija",revision:4}],links:[{id:"a1",from:"DATASET-004",to:"ANALYSIS-011",relation:"uses"},{id:"a2",from:"ANALYSIS-011",to:"RESULT-031",relation:"produces"},{id:"a3",from:"RESULT-031",to:"CLAIM-014",relation:"supports"},{id:"a4",from:"CLAIM-014",to:"S5.2",relation:"appears-in"},{id:"a5",from:"S5.2",to:"K6",relation:"contributes-to"}]},"DATASET-004"),[]);
 const reviewItems=useMemo<ReviewQueueItem[]>(()=>danielDelta.map(x=>({object:x.object,reason:x.kind==="new"?"new":"changed",contextLabel:x.object.type==="conclusion"?"Zaključak §6":x.object.type==="section"?"Rasprava §5.2":"Akademski objekt"})),[danielDelta]);
 const readiness=useMemo(()=>evaluateAcademicReadiness({graphIssues:[],coverage:danielCoverage,evidence:[{id:"EB-014",status:"RECHECK_REQUIRED"}],protectedFacts:[{id:"N-001",status:"UNCHANGED"},{id:"STAT-001",status:"UNCHANGED"}],analysis:[{id:"RESULT-031",status:"CURRENT"}],instructionIssues:[],lekta:{status:"not-run",findingCount:0}}),[danielCoverage]);
 return <section className="card mentor-command-demo" aria-label="Mentor Command Center">
  <div><strong>Mentor Command Center</strong><p className="hint">Radna lista proizlazi iz workflow činjenica. Nema risk scorea ni procjene akademskog poštenja.</p></div>
  <div className="row">{(["mentor","student","none","all"] as const).map(v=><button key={v} className={"btn "+(view===v?"btn-primary":"")} aria-pressed={view===v} onClick={()=>{setView(v);setSelected(null)}}>{LABEL[v]} ({v==="all"?queue.length:groups[v].length})</button>)}</div>
  {!project?<div style={{marginTop:".75rem"}}>{shown.map(item=><button key={item.projectId} className="card" style={{display:"block",width:"100%",textAlign:"left"}} onClick={()=>setSelected(item.projectId)}><strong>{item.studentLabel} · {item.workLabel}</strong><p className="hint">Zadnja aktivnost: {item.lastActivityAt.slice(0,10)}</p>{item.reasons.length?<p>{item.reasons.map(r=>`${r.count} × ${REASON[r.kind]}`).join(" · ")}</p>:<p className="hint">{item.waitingOn==="student"?"Student još radi na sljedećoj verziji.":"Nema otvorene akcije."}</p>}</button>)}</div>:
  <div className="card" style={{marginTop:".75rem"}}><button className="btn" onClick={()=>setSelected(null)}>← Natrag na studente</button><h3>{project.studentLabel} · {project.workLabel}</h3><p className="hint">{LABEL[project.waitingOn]}</p><div className="row"><a className="btn btn-primary" href="#mentor-process-view">Proces pisanja</a>{project.projectId==="p-daniel"?<><button className="btn" onClick={()=>setDetails("review")}>Promjene i coverage</button><button className="btn" onClick={()=>setDetails("revisions")}>Dorade</button><button className="btn" onClick={()=>setDetails("arguments")}>Argumenti</button><button className="btn" onClick={()=>setDetails("checks")}>Provjere</button><button className="btn btn-primary" onClick={()=>{setReviewQueue(createReviewQueue(reviewItems));setDetails("queue");setNote("")}}>Pokreni pregled</button></>:null}</div>{project.projectId!=="p-daniel"||details==="summary"?project.reasons.map(r=><p key={r.kind}><b>{r.count}</b> · {REASON[r.kind]}</p>):details==="review"?<div><label className="row"><input type="checkbox" checked={language} onChange={e=>setLanguage(e.target.checked)}/> Uključi čisto jezične promjene</label><h4>Promijenjeno od zadnjeg pregleda</h4>{danielDelta.map(x=><p key={x.object.id}><b>{x.object.label}</b> · {x.kind==="new"?"novo za pregled":`revizija ${x.lastReviewedRevision} → ${x.currentRevision}`} · {x.changeKinds.join(", ")||"nova stavka"}</p>)}<h4>Coverage Map</h4>{danielCoverage.map(x=><p key={x.object.id}>{x.object.label} · <b>{x.state==="CURRENTLY_COVERED"?"aktualno pregledano":x.state==="CHANGED_SINCE_REVIEW"?"promijenjeno nakon pregleda":"nikad pregledano"}</b></p>)}</div>:details==="revisions"?<div><h4>Dorade</h4><p><b>2</b> odgovora studenta čekaju mentorski pregled.</p><p><b>1</b> objekt promijenjen je nakon ranije prihvaćene revizije.</p><p className="hint">Promjenu statusa dorade mentor radi u postojećem Dorada workflowu; Command Center ovdje samo sažima stanje.</p></div>:details==="arguments"?<div><h4>Argumentacijski put</h4>{argumentPath.map(x=><p key={x.target.id}>{x.target.label}</p>)}</div>:details==="checks"?<div><h4>Academic Readiness</h4><p><b>{readiness.readyForSubmission?"Nema blokera":"Postoje otvoreni blokeri"}</b></p>{readiness.findings.map(x=><p key={x.id}><b>{x.severity==="blocker"?"BLOKER":"UPOZORENJE"}</b> · {x.message}</p>)}</div>:<ReviewQueuePanel state={reviewQueue} note={note} setNote={setNote} setState={setReviewQueue}/>} </div>}
 </section>;
}
