"use client";
import{useState}from"react";import{searchResearchMemory,type MemoryItem}from"@/domain/memory";
const ITEMS:MemoryItem[]=[
{id:"m1",ownerId:"student",projectId:"diplomski",projectLabel:"Trenutačni diplomski",type:"claim",title:"Inkrementalizam",text:"Lindblom i sukcesivne ograničene usporedbe",provenance:"§2 · CLAIM-014",access:"owned"},
{id:"m2",ownerId:"student",projectId:"seminar-2025",projectLabel:"Seminarski rad 2025.",type:"decision",title:"Teorijski okvir",text:"Usporedba inkrementalizma i mixed-scanning pristupa",provenance:"Decision D4",access:"owned"},
{id:"m3",ownerId:"student",projectId:"library",projectLabel:"Vlastita literatura",type:"source",title:"Lindblom 1959",text:"The Science of Muddling Through · inkrementalizam",provenance:"Biblioteka izvora",access:"owned"},
{id:"hidden",ownerId:"other",projectId:"private",projectLabel:"Tuđi privatni rad",type:"claim",title:"Inkrementalizam",text:"privatni tekst o inkrementalizmu",provenance:"private",access:"owned"}];
export default function ResearchMemoryDemo(){const[q,setQ]=useState("inkrementalizam");const[run,setRun]=useState(false);const results=run?searchResearchMemory(ITEMS,"student",q):[];
return <section className="memory-demo"><h2 style={{fontSize:"1.1rem",margin:"0 0 .25rem"}}>Research Memory</h2><p className="hint">Pretražuje dostupne akademske objekte; ne kopira ih automatski u trenutačni rad.</p><div className="card"><input className="input" value={q} onChange={e=>setQ(e.target.value)} aria-label="Pretraži istraživačku memoriju"/><button className="btn btn-primary" style={{marginTop:".6rem"}} onClick={()=>setRun(true)}>Pretraži</button></div>{run?<div className="card" data-memory-results=""><strong>Rezultati ({results.length})</strong>{results.map(r=><div className="memory-result" key={r.item.id}><b>{r.item.title}</b><span>{r.item.projectLabel} · {r.item.type}</span><span className="hint">{r.item.provenance} · scope: {r.item.access}</span><span className="hint">Podudaranje: {r.matchedTerms.join(", ")}</span></div>)}{results.length===0?<p className="hint">Nema dostupnih rezultata.</p>:null}<p className="hint">Privatni sadržaj drugih korisnika nije dio rezultata.</p></div>:null}</section>}
