import Dexie,{type Table}from"dexie";import{appendAcademicObjectBinding,type AcademicObjectNodeBinding,type AcademicObjectRegistry,type NewAcademicObjectBinding}from"@/domain/academic-graph/academic-object-registry";
export const ACADEMIC_OBJECT_REGISTRY_DB_NAME="pisac-academic-object-registry";
export class AcademicObjectRegistryDatabase extends Dexie{bindings!:Table<AcademicObjectNodeBinding,string>;constructor(name=ACADEMIC_OBJECT_REGISTRY_DB_NAME){super(name);this.version(1).stores({bindings:"bindingId, objectId, [objectId+bindingVersion], boundAt"});}}
export async function openAcademicObjectRegistry(name=ACADEMIC_OBJECT_REGISTRY_DB_NAME):Promise<{ok:true;db:AcademicObjectRegistryDatabase}|{ok:false;reason:"unavailable"|"open-failed"}>{try{if(typeof indexedDB==="undefined"||indexedDB===null)return{ok:false,reason:"unavailable"};const db=new AcademicObjectRegistryDatabase(name);await db.open();return{ok:true,db};}catch{return{ok:false,reason:"open-failed"};}}
export async function loadAcademicObjectRegistry(db:AcademicObjectRegistryDatabase):Promise<{ok:true;registry:AcademicObjectRegistry}|{ok:false;reason:"invalid-registry"}>{
 const rows=await db.bindings.toArray();const ordered=[...rows].sort((a,b)=>a.objectId.localeCompare(b.objectId)||a.bindingVersion-b.bindingVersion||a.bindingId.localeCompare(b.bindingId));let registry:AcademicObjectRegistry={bindings:[]};
 try{for(const row of ordered){const expected=appendAcademicObjectBinding(registry,{bindingId:row.bindingId,objectId:row.objectId,objectType:row.objectType,objectRevision:row.objectRevision,nodeId:row.nodeId,boundAt:row.boundAt});const actual=expected.bindings.at(-1)!;if(actual.bindingVersion!==row.bindingVersion||actual.previousBindingId!==row.previousBindingId)throw new Error("invalid");registry=expected;}return{ok:true,registry};}catch{return{ok:false,reason:"invalid-registry"};}
}
export async function appendPersistedAcademicBinding(db:AcademicObjectRegistryDatabase,input:NewAcademicObjectBinding):Promise<AcademicObjectNodeBinding>{
 return db.transaction("rw",db.bindings,async()=>{if(await db.bindings.get(input.bindingId))throw new Error("academic-object-registry: duplicate binding");const loaded=await loadAcademicObjectRegistry(db);if(!loaded.ok)throw new Error("academic-object-registry: invalid-registry");const next=appendAcademicObjectBinding(loaded.registry,input).bindings.at(-1)!;await db.bindings.add(structuredClone(next));return next;});
}
