import{describe,expect,it}from"vitest";import{createForensicEvent,type ForensicEvent}from"./ledger";import{buildMentorProcessView,forensicDrillDown}from"./mentor-process";
const e=(sequence:number,revision:number,nodeId:string,payload?:ForensicEvent["payload"])=>createForensicEvent({schemaVersion:1,id:"e"+sequence,documentId:"d",sequence,revision,occurredAt:`2026-09-29T09:00:0${sequence}Z`,actorId:"student",actorRole:"student",payload:payload??{kind:"insert-text",nodeId,offset:0,text:String(sequence)}});
const events=[e(1,3,"intro"),e(2,3,"methods",{kind:"paste",nodeId:"methods",offset:0,text:"PASTE"}),e(3,4,"methods"),e(4,4,"private")];
describe("Mentor Process View",()=>{
 it("never projects events beyond sequence boundary",()=>{const v=buildMentorProcessView({events,integrityVerified:true,scope:{throughSequence:2}});expect(v.eventCount).toBe(2);expect(v.timeline.flatMap(x=>x.sourceEventIds)).not.toContain("e3");});
 it("scopes both timeline and rhythm to allowed revisions",()=>{const v=buildMentorProcessView({events,integrityVerified:true,scope:{throughSequence:4,allowedRevisions:[3]}});expect(v.eventCount).toBe(2);expect(v.timeline.flatMap(x=>x.sourceEventIds)).toEqual(expect.arrayContaining(["e1","e2"]));expect(v.timeline.flatMap(x=>x.sourceEventIds)).not.toContain("e3");expect(v.rhythm.manualInsertEvents).toBe(1);});
 it("scopes node-addressed events to allowed nodes",()=>{const v=buildMentorProcessView({events,integrityVerified:true,scope:{throughSequence:4,allowedNodeIds:["methods"]}});expect(v.timeline.flatMap(x=>x.sourceEventIds)).toEqual(expect.arrayContaining(["e2","e3"]));expect(v.timeline.flatMap(x=>x.sourceEventIds)).not.toContain("e4");});
 it("filters semantic categories without losing forensic provenance",()=>{const v=buildMentorProcessView({events,integrityVerified:true,filter:"paste",scope:{throughSequence:4}});expect(v.timeline).toHaveLength(1);expect(v.timeline[0]).toMatchObject({kind:"paste",sourceEventIds:["e2"]});});
 it("drill-down cannot reveal hidden events even when requested by id",()=>expect(forensicDrillDown(events,["e2","e3","e4"],{throughSequence:4,allowedRevisions:[3],allowedNodeIds:["methods"]}).map(x=>x.id)).toEqual(["e2"]));
 it("does not claim verified integrity unless caller verified the ledger",()=>expect(buildMentorProcessView({events,integrityVerified:false,scope:{throughSequence:4}}).integrity).toBe("unverified"));
});
