export type EvolutionSession={sessionId:string;startedAt:string;eventCount:number};
export type AcademicObjectBinding={objectId:string;objectType:string;revision:number;sessionId:string;eventIndexes:readonly number[];beforeText:string;afterText:string;evidenceIds:readonly string[]};
export type ObjectEvolutionRevision=AcademicObjectBinding&{startedAt:string;addedEvidenceIds:readonly string[];removedEvidenceIds:readonly string[]};
export type ObjectEvolution={objectId:string;revisions:readonly ObjectEvolutionRevision[]};
export function buildObjectEvolution(objectId:string,sessions:readonly EvolutionSession[],bindings:readonly AcademicObjectBinding[]):ObjectEvolution{
 const bySession=new Map(sessions.map(s=>[s.sessionId,s]));const selected=bindings.filter(b=>b.objectId===objectId);const seen=new Map<number,AcademicObjectBinding>();
 for(const b of selected){if(!Number.isSafeInteger(b.revision)||b.revision<1)throw new Error("buildObjectEvolution: invalid revision");const s=bySession.get(b.sessionId);if(!s)throw new Error("buildObjectEvolution: missing session");let last=-1;const eventSeen=new Set<number>();for(const i of b.eventIndexes){if(!Number.isSafeInteger(i)||i<0||i>=s.eventCount)throw new Error("buildObjectEvolution: event out of range");if(eventSeen.has(i)||i<=last)throw new Error("buildObjectEvolution: invalid event order");eventSeen.add(i);last=i;}if(new Set(b.evidenceIds).size!==b.evidenceIds.length)throw new Error("buildObjectEvolution: duplicate evidence");const prev=seen.get(b.revision);if(prev&&(prev.sessionId!==b.sessionId||prev.beforeText!==b.beforeText||prev.afterText!==b.afterText||JSON.stringify(prev.eventIndexes)!==JSON.stringify(b.eventIndexes)||JSON.stringify(prev.evidenceIds)!==JSON.stringify(b.evidenceIds)))throw new Error("buildObjectEvolution: conflicting revision");seen.set(b.revision,b);}
 const ordered=[...seen.values()].sort((a,b)=>a.revision-b.revision);let previousEvidence=new Set<string>();const revisions:ObjectEvolutionRevision[]=[];
 for(const b of ordered){const s=bySession.get(b.sessionId)!;const current=new Set(b.evidenceIds);revisions.push({...b,startedAt:s.startedAt,addedEvidenceIds:[...current].filter(x=>!previousEvidence.has(x)),removedEvidenceIds:[...previousEvidence].filter(x=>!current.has(x))});previousEvidence=current;}
 return{objectId,revisions};
}
