import{test,expect}from"@playwright/test";
test.describe("revision-specific EvidenceBasis",()=>{
 test("evidence must be explicitly verified for each claim revision",async({page})=>{
  await page.goto("/demo");const editor=page.getByRole("textbox",{name:"Tekst rada"});let registry=page.getByRole("region",{name:"Academic Object Registry"});const bind=registry.getByRole("button",{name:"Poveži CLAIM-014 s ovim odlomkom"});await expect(bind).toBeEnabled();await editor.click();await bind.click();await expect(registry.getByTestId("claim-binding")).toContainText("binding v1");
  let evidence=registry.getByLabel("EvidenceBasis CLAIM-014");await expect(evidence).toContainText("rev. 4");await expect(evidence).toContainText("RECHECK_REQUIRED");await expect(evidence).toContainText("verdict: nije provjeren");await evidence.getByRole("button",{name:"Potvrdi provjeru za rev. 4"}).click();await expect(evidence).toContainText("VALID");await expect(evidence).toContainText("basis: DEMO-BASIS-R4");await expect(evidence).toContainText("verdict: supports");
  const panel=page.getByRole("region",{name:"Stvarni proces pisanja"});await panel.getByRole("button",{name:"Pokreni lokalno bilježenje"}).click();await editor.pressSequentially("A");await expect(panel.getByTestId("persisted-count")).toHaveText("1");await expect(page.locator('[data-sync-state="LOCAL_DURABLE"]')).toBeVisible();await panel.getByRole("button",{name:"Završi i provjeri sesiju"}).click();await registry.getByLabel("Draft akademske revizije").getByRole("button",{name:"Zaključi akademsku reviziju"}).click();
  evidence=registry.getByLabel("EvidenceBasis CLAIM-014");await expect(evidence).toContainText("rev. 5");await expect(evidence).toContainText("RECHECK_REQUIRED");await expect(evidence).toContainText("Ne tvrdi da je izvor netočan.");await evidence.getByRole("button",{name:"Potvrdi provjeru za rev. 5"}).click();await expect(evidence).toContainText("VALID");await expect(evidence).toContainText("basis: DEMO-BASIS-R5");await expect(evidence).toContainText("verdict: supports");
  await page.reload();registry=page.getByRole("region",{name:"Academic Object Registry"});evidence=registry.getByLabel("EvidenceBasis CLAIM-014");await expect(evidence).toContainText("rev. 5");await expect(evidence).toContainText("VALID");await expect(evidence).toContainText("basis: DEMO-BASIS-R5");await expect(evidence).toContainText("verdict: supports");
 });
});
