import{test,expect}from"@playwright/test";
test.describe("revision-driven mentor projection",()=>{
 test("seal makes review stale and evidence recheck remains independent from mentor coverage",async({page})=>{
  await page.goto("/demo");const editor=page.getByRole("textbox",{name:"Tekst rada"});const registry=page.getByRole("region",{name:"Academic Object Registry"});await editor.click();await registry.getByRole("button",{name:"Poveži CLAIM-014 s ovim odlomkom"}).click();let mentor=registry.getByLabel("Mentor projection CLAIM-014");await expect(mentor).toContainText("CURRENTLY_COVERED");await expect(mentor).toContainText("Review Delta: 0");
  const panel=page.getByRole("region",{name:"Stvarni proces pisanja"});await panel.getByRole("button",{name:"Pokreni lokalno bilježenje"}).click();await editor.pressSequentially("A");await expect(panel.getByTestId("persisted-count")).toHaveText("1");await expect(page.locator('[data-sync-state="LOCAL_DURABLE"]')).toBeVisible();await panel.getByRole("button",{name:"Završi i provjeri sesiju"}).click();await registry.getByLabel("Draft akademske revizije").getByRole("button",{name:"Zaključi akademsku reviziju"}).click();
  mentor=registry.getByLabel("Mentor projection CLAIM-014");await expect(mentor).toContainText("CHANGED_SINCE_REVIEW");await expect(mentor).toContainText("Review Delta: 1");await expect(mentor).toContainText("Readiness blockeri: 1");await expect(mentor).toContainText("čeka: mentor");
  await mentor.getByRole("button",{name:"Mentor označi rev. 5 pregledanom"}).click();await expect(mentor).toContainText("CURRENTLY_COVERED");await expect(mentor).toContainText("Review Delta: 0");await expect(mentor).toContainText("Readiness blockeri: 1");await expect(mentor).toContainText("čeka: mentor");
  const evidence=registry.getByLabel("EvidenceBasis CLAIM-014");await evidence.getByRole("button",{name:"Potvrdi provjeru za rev. 5"}).click();await expect(mentor).toContainText("Readiness blockeri: 0");await expect(mentor).toContainText("čeka: none");
 });
});