import{describe,expect,it}from"vitest";import{projectRevisionMentorState}from"./revision-projector";
const binding={documentId:"doc",bindingId:"b5",objectId:"CLAIM-014",objectType:"claim"as const,objectRevision:5,nodeId:"n1",boundAt:"2026-10-02T11:00:00Z",bindingVersion:2,previousBindingId:"b4"};
const revision={revisionId:"rev5",documentId:"doc",objectId:"CLAIM-014",revision:5,baseRevision:4,bindingId:"b4",openedAt:"2026-10-02T10:00:00Z",lastActivityAt:"2026-10-02T10:30:00Z",sealedAt:"2026-10-02T11:00:00Z",activity:[{sessionId:"s1",eventIndexes:[0]}],afterText:"x"};
const base={projectId:"p",studentId:"s",studentLabel:"Student",workLabel:"Rad",reviewerId:"mentor",documentId:"doc",objectLabel:"Tvrdnja",binding,revisions:[revision],reviews:[],evidence:[{id:"e1",status:"RECHECK_REQUIRED"as const}],evidenceRecheckOwner:"student"as const};
describe("revision-driven mentor projection",()=>{
 it("shows an unreviewed current revision as mentor work while retaining the student evidence blocker",()=>{const p=projectRevisionMentorState(base);expect(p.coverage[0].state).toBe("NEVER_REVIEWED");expect(p.delta).toHaveLength(1);expect(p.actionState).toEqual({mentor:{changedReviewCount:0,neverReviewedCount:1,readinessBlockerCount:0},student:{readinessBlockerCount:1,revisionRequestPending:false},waitingOn:"mentor"});});
 it("moves to the student after the mentor reviews the exact revision",()=>{const p=projectRevisionMentorState({...base,reviews:[{documentId:"doc",bindingId:"b5",id:"r5",reviewerId:"mentor",objectId:"CLAIM-014",reviewedRevision:5,reviewedAt:"2026-10-02T11:05:00Z",status:"reviewed"as const}]});expect(p.coverage[0].state).toBe("CURRENTLY_COVERED");expect(p.delta).toHaveLength(0);expect(p.actionState.student.readinessBlockerCount).toBe(1);expect(p.queue.waitingOn).toBe("student");});
 it("moves to none only after review coverage and evidence freshness are both current",()=>{const p=projectRevisionMentorState({...base,reviews:[{documentId:"doc",bindingId:"b5",id:"r5",reviewerId:"mentor",objectId:"CLAIM-014",reviewedRevision:5,reviewedAt:"2026-10-02T11:05:00Z",status:"reviewed"as const}],evidence:[{id:"e1",status:"VALID"as const}]});expect(p.queue.waitingOn).toBe("none");expect(p.actionState).toMatchObject({mentor:{changedReviewCount:0,neverReviewedCount:0,readinessBlockerCount:0},student:{readinessBlockerCount:0,revisionRequestPending:false}});});
 it("can assign an evidence recheck to the mentor without changing its readiness meaning",()=>{const p=projectRevisionMentorState({...base,reviews:[{documentId:"doc",bindingId:"b5",id:"r5",reviewerId:"mentor",objectId:"CLAIM-014",reviewedRevision:5,reviewedAt:"2026-10-02T11:05:00Z",status:"reviewed"as const}],evidenceRecheckOwner:"mentor"as const});expect(p.actionState.mentor.readinessBlockerCount).toBe(1);expect(p.actionState.student.readinessBlockerCount).toBe(0);expect(p.queue.waitingOn).toBe("mentor");});
 it("keeps an exact-revision needs-work review covered but waiting on the student",()=>{const p=projectRevisionMentorState({...base,reviews:[{documentId:"doc",bindingId:"b5",id:"r5",reviewerId:"mentor",objectId:"CLAIM-014",reviewedRevision:5,reviewedAt:"2026-10-02T11:05:00Z",status:"needs-work"as const}],evidence:[{id:"e1",status:"VALID"as const}]});expect(p.coverage[0].state).toBe("CURRENTLY_COVERED");expect(p.delta).toHaveLength(0);expect(p.actionState.student.revisionRequestPending).toBe(true);expect(p.queue.waitingOn).toBe("student");});
 it("invalidates review coverage when the object is rebound to a new node at the same academic revision",()=>{const p=projectRevisionMentorState({...base,reviews:[{documentId:"doc",bindingId:"old-b5",id:"r5-old",reviewerId:"mentor",objectId:"CLAIM-014",reviewedRevision:5,reviewedAt:"2026-10-02T11:01:00Z",status:"reviewed"as const}]});expect(p.coverage[0].state).toBe("CHANGED_SINCE_REVIEW");expect(p.delta[0]).toMatchObject({lastReviewedRevision:5,currentRevision:5,changeKinds:["content","structure"]});expect(p.queue.waitingOn).toBe("mentor");});
 it("reports CHANGED_SINCE_REVIEW when only the previous revision was reviewed",()=>{const p=projectRevisionMentorState({...base,reviews:[{documentId:"doc",bindingId:"b4",id:"r4",reviewerId:"mentor",objectId:"CLAIM-014",reviewedRevision:4,reviewedAt:"2026-10-02T10:00:00Z",status:"reviewed"as const}]});expect(p.coverage[0].state).toBe("CHANGED_SINCE_REVIEW");expect(p.delta[0]).toMatchObject({kind:"changed",lastReviewedRevision:4,currentRevision:5});expect(p.actionState.mentor.changedReviewCount).toBe(1);});
 it("rejects two conflicting same-time reviews for one binding instead of using id tie-breaks",()=>{const reviews=[{documentId:"doc",bindingId:"b5",id:"a",reviewerId:"mentor",objectId:"CLAIM-014",reviewedRevision:5,reviewedAt:"2026-10-02T11:05:00Z",status:"reviewed"as const},{documentId:"doc",bindingId:"b5",id:"b",reviewerId:"mentor",objectId:"CLAIM-014",reviewedRevision:5,reviewedAt:"2026-10-02T11:05:00Z",status:"needs-work"as const}];expect(()=>projectRevisionMentorState({...base,reviews})).toThrow("ambiguous review order");});
 it("ignores another document's review and rejects a forged future review",()=>{const other={documentId:"other",bindingId:"b5",id:"other",reviewerId:"mentor",objectId:"CLAIM-014",reviewedRevision:5,reviewedAt:"2026-10-02T11:05:00Z",status:"reviewed"as const};expect(projectRevisionMentorState({...base,reviews:[other]}).coverage[0].state).toBe("NEVER_REVIEWED");expect(()=>projectRevisionMentorState({...base,reviews:[{...other,documentId:"doc",reviewedRevision:6}]})).toThrow("future review");});
 it("fails closed while revision DB is one phase ahead of the registry",()=>expect(()=>projectRevisionMentorState({...base,binding:{...binding,objectRevision:4},revisions:[revision]})).toThrow("registry behind revision"));
});
