import{describe,expect,it}from"vitest";import{academicObjectBindingIntervals,appendAcademicObjectBinding,currentAcademicObjectBinding,type AcademicObjectRegistry}from"./academic-object-registry";
const empty:AcademicObjectRegistry={bindings:[]};
describe("academic object registry",()=>{
 it("creates the first explicit object-to-node binding",()=>{const r=appendAcademicObjectBinding(empty,{bindingId:"b1",objectId:"CLAIM-014",objectType:"claim",objectRevision:3,nodeId:"node-a",boundAt:"2026-09-30T18:00:00Z"});expect(currentAcademicObjectBinding(r,"CLAIM-014")).toMatchObject({bindingId:"b1",nodeId:"node-a",bindingVersion:1,previousBindingId:null});});
 it("rebinds append-only and preserves the historical node",()=>{let r=appendAcademicObjectBinding(empty,{bindingId:"b1",objectId:"CLAIM-014",objectType:"claim",objectRevision:3,nodeId:"node-a",boundAt:"2026-09-30T18:00:00Z"});r=appendAcademicObjectBinding(r,{bindingId:"b2",objectId:"CLAIM-014",objectType:"claim",objectRevision:4,nodeId:"node-b",boundAt:"2026-09-30T19:00:00Z"});expect(r.bindings.map(x=>[x.bindingVersion,x.nodeId,x.previousBindingId])).toEqual([[1,"node-a",null],[2,"node-b","b1"]]);});
 it("rejects duplicate binding ids and time travel",()=>{const r=appendAcademicObjectBinding(empty,{bindingId:"b1",objectId:"CLAIM-014",objectType:"claim",objectRevision:3,nodeId:"node-a",boundAt:"2026-09-30T18:00:00Z"});expect(()=>appendAcademicObjectBinding(r,{bindingId:"b1",objectId:"CLAIM-015",objectType:"claim",objectRevision:1,nodeId:"node-b",boundAt:"2026-09-30T19:00:00Z"})).toThrow("duplicate binding");expect(()=>appendAcademicObjectBinding(r,{bindingId:"b2",objectId:"CLAIM-014",objectType:"claim",objectRevision:2,nodeId:"node-b",boundAt:"2026-09-30T17:00:00Z"})).toThrow();});
 it("rejects equal binding timestamps because event ordering would be ambiguous at millisecond resolution",()=>{const r=appendAcademicObjectBinding(empty,{bindingId:"b1",objectId:"CLAIM-014",objectType:"claim",objectRevision:3,nodeId:"node-a",boundAt:"2026-09-30T18:00:00.000Z"});expect(()=>appendAcademicObjectBinding(r,{bindingId:"b2",objectId:"CLAIM-014",objectType:"claim",objectRevision:3,nodeId:"node-b",boundAt:"2026-09-30T18:00:00.000Z"})).toThrow("non-increasing time");});
 it("closes the old node interval when an object is rebound",()=>{let r=appendAcademicObjectBinding(empty,{bindingId:"b1",objectId:"CLAIM-014",objectType:"claim",objectRevision:3,nodeId:"node-a",boundAt:"2026-09-30T18:00:00Z"});r=appendAcademicObjectBinding(r,{bindingId:"b2",objectId:"CLAIM-014",objectType:"claim",objectRevision:4,nodeId:"node-b",boundAt:"2026-09-30T19:00:00Z"});expect(academicObjectBindingIntervals(r,"CLAIM-014").map(x=>[x.binding.nodeId,x.effectiveFrom,x.effectiveUntil])).toEqual([["node-a","2026-09-30T18:00:00Z","2026-09-30T19:00:00Z"],["node-b","2026-09-30T19:00:00Z",null]]);});
 it("allows multiple academic objects to reference the same block node",()=>{let r=appendAcademicObjectBinding(empty,{bindingId:"b1",objectId:"CLAIM-014",objectType:"claim",objectRevision:1,nodeId:"node-a",boundAt:"2026-09-30T18:00:00Z"});r=appendAcademicObjectBinding(r,{bindingId:"b2",objectId:"CLAIM-015",objectType:"claim",objectRevision:1,nodeId:"node-a",boundAt:"2026-09-30T18:01:00Z"});expect(r.bindings).toHaveLength(2);});
});