import{describe,expect,it}from"vitest";import{beginAcademicRevisionDraft,sealAcademicRevisionDraft,type AcademicRevisionLedger}from"./academic-revision-lifecycle";
const empty:AcademicRevisionLedger={revisions:[],drafts:[]};
const draft=(overrides:Partial<Parameters<typeof beginAcademicRevisionDraft>[1]>={})=>({draftId:"d1",documentId:"doc",objectId:"CLAIM-014",baseRevision:4,bindingId:"b4",openedAt:"2026-10-02T10:00:00Z",activity:[{sessionId:"s1",eventIndexes:[0,1]}],afterText:"B",...overrides});
describe("academic revision lifecycle",()=>{
 it("opens one draft from verified activity without incrementing per event",()=>{const l=beginAcademicRevisionDraft(empty,draft());expect(l.drafts).toHaveLength(1);expect(l.drafts[0]).toMatchObject({documentId:"doc",objectId:"CLAIM-014",baseRevision:4,afterText:"B"});});
 it("requires later updates to contain the already persisted activity prefix",()=>{let l=beginAcademicRevisionDraft(empty,draft());l=beginAcademicRevisionDraft(l,draft({activity:[{sessionId:"s1",eventIndexes:[0,1,2]}],afterText:"C"}));expect(l.drafts[0].activity[0].eventIndexes).toEqual([0,1,2]);expect(l.drafts[0].afterText).toBe("C");expect(()=>beginAcademicRevisionDraft(l,draft({activity:[{sessionId:"s1",eventIndexes:[0]}],afterText:"A"}))).toThrow("stale activity");});
 it("seals exactly base revision plus one using the verified draft snapshot",()=>{const l=beginAcademicRevisionDraft(empty,draft({afterText:null}));const s=sealAcademicRevisionDraft(l,{draftId:"d1",revisionId:"r5",sealedAt:"2026-10-02T11:00:00Z"});expect(s.revisions[0]).toMatchObject({documentId:"doc",objectId:"CLAIM-014",revision:5,baseRevision:4,bindingId:"b4",afterText:null});expect(s.drafts).toHaveLength(0);});
 it("keeps identical object ids independent across documents",()=>{let l=beginAcademicRevisionDraft(empty,draft());l=beginAcademicRevisionDraft(l,draft({draftId:"d2",documentId:"other",bindingId:"other-b"}));expect(l.drafts).toHaveLength(2);});
 it("rejects a stale base after a revision is sealed",()=>{let l=beginAcademicRevisionDraft(empty,draft());l=sealAcademicRevisionDraft(l,{draftId:"d1",revisionId:"r5",sealedAt:"2026-10-02T11:00:00Z"});expect(()=>beginAcademicRevisionDraft(l,draft({draftId:"d2"}))).toThrow("stale base");});
});
