import{describe,expect,it}from"vitest";import{attachEvidenceReview,evidenceReviewAssessmentForClaimRevision,verifyEvidenceReviewForRevision,type EvidenceReviewLedger}from"./evidence-basis-lifecycle";
const empty:EvidenceReviewLedger={links:[],verifications:[]};
const link={documentId:"doc",linkId:"e1",claimId:"CLAIM-014",sourceId:"SRC-1",attachedRevision:4,attachedAt:"2026-10-02T10:00:00Z"};
describe("revision-specific EvidenceBasis review",()=>{
 it("is VALID only for the exact claim revision and exact basis snapshot that was verified",()=>{let l=attachEvidenceReview(empty,link);l=verifyEvidenceReviewForRevision(l,{documentId:"doc",verificationId:"v4",linkId:"e1",basisId:"BASIS-R4",claimRevision:4,verifiedAt:"2026-10-02T10:10:00Z",verdict:"supports"});expect(evidenceReviewAssessmentForClaimRevision(l,"doc","e1",4)).toEqual({reviewStatus:"VALID",basisId:"BASIS-R4",verdict:"supports"});expect(evidenceReviewAssessmentForClaimRevision(l,"doc","e1",5)).toEqual({reviewStatus:"RECHECK_REQUIRED",basisId:null,verdict:null});});
 it("keeps freshness separate from substantive verdict",()=>{let l=attachEvidenceReview(empty,link);l=verifyEvidenceReviewForRevision(l,{documentId:"doc",verificationId:"v4",linkId:"e1",basisId:"BASIS-R4",claimRevision:4,verifiedAt:"2026-10-02T10:10:00Z",verdict:"challenges"});expect(evidenceReviewAssessmentForClaimRevision(l,"doc","e1",4)).toEqual({reviewStatus:"VALID",basisId:"BASIS-R4",verdict:"challenges"});});
 it("does not project a source link onto revisions before it was attached",()=>{const l=attachEvidenceReview(empty,link);expect(evidenceReviewAssessmentForClaimRevision(l,"doc","e1",3)).toBeNull();});
 it("rejects retroactive verification before the attachment revision or time",()=>{const l=attachEvidenceReview(empty,link);expect(()=>verifyEvidenceReviewForRevision(l,{documentId:"doc",verificationId:"old",linkId:"e1",basisId:"BASIS-R3",claimRevision:3,verifiedAt:"2026-10-02T10:10:00Z",verdict:"supports"})).toThrow("before attachment revision");expect(()=>verifyEvidenceReviewForRevision(l,{documentId:"doc",verificationId:"early",linkId:"e1",basisId:"BASIS-R4",claimRevision:4,verifiedAt:"2026-10-02T09:59:59Z",verdict:"supports"})).toThrow("before attachment");});
 it("allows only one immutable review verification per link and claim revision",()=>{let l=attachEvidenceReview(empty,link);l=verifyEvidenceReviewForRevision(l,{documentId:"doc",verificationId:"v4",linkId:"e1",basisId:"BASIS-R4",claimRevision:4,verifiedAt:"2026-10-02T10:10:00Z",verdict:"supports"});expect(()=>verifyEvidenceReviewForRevision(l,{documentId:"doc",verificationId:"v4b",linkId:"e1",basisId:"OTHER-R4",claimRevision:4,verifiedAt:"2026-10-02T10:20:00Z",verdict:"challenges"})).toThrow("revision already verified");});
 it("keeps identical link ids independent across documents",()=>{let l=attachEvidenceReview(empty,link);l=attachEvidenceReview(l,{...link,documentId:"other"});expect(l.links).toHaveLength(2);});
});
