import{describe,expect,it}from"vitest";import{attachEvidenceReview,verifyEvidenceReviewForRevision}from"./evidence-basis-lifecycle";import{evidenceReadinessInput}from"./evidence-readiness-adapter";import{evaluateAcademicReadiness}from"@/domain/readiness";
const link={documentId:"doc",linkId:"e1",claimId:"C",sourceId:"S",attachedRevision:4,attachedAt:"2026-10-02T10:00:00Z"};
describe("EvidenceBasis readiness adapter",()=>{
 it("projects a previously reviewed source as RECHECK_REQUIRED for a new claim revision",()=>{let l=attachEvidenceReview({links:[],verifications:[]},link);l=verifyEvidenceReviewForRevision(l,{documentId:"doc",verificationId:"v4",linkId:"e1",basisId:"BASIS-R4",claimRevision:4,verifiedAt:"2026-10-02T10:10:00Z",verdict:"supports"});expect(evidenceReadinessInput(l,"doc","C",5,[{basisId:"BASIS-R4",status:"VALID"}])).toEqual([{id:"e1",status:"RECHECK_REQUIRED"}]);});
 it("requires both exact-revision review coverage and a currently VALID canonical basis snapshot",()=>{let l=attachEvidenceReview({links:[],verifications:[]},link);l=verifyEvidenceReviewForRevision(l,{documentId:"doc",verificationId:"v4",linkId:"e1",basisId:"BASIS-R4",claimRevision:4,verifiedAt:"2026-10-02T10:10:00Z",verdict:"supports"});expect(evidenceReadinessInput(l,"doc","C",4,[{basisId:"BASIS-R4",status:"RECHECK_REQUIRED"}])).toEqual([{id:"e1",status:"RECHECK_REQUIRED"}]);expect(evidenceReadinessInput(l,"doc","C",4,[{basisId:"BASIS-R4",status:"VALID"}])).toEqual([{id:"e1",status:"VALID"}]);});
 it("does not turn a challenging but current review into a blocker when the basis snapshot itself is valid",()=>{let l=attachEvidenceReview({links:[],verifications:[]},link);l=verifyEvidenceReviewForRevision(l,{documentId:"doc",verificationId:"v4",linkId:"e1",basisId:"BASIS-R4",claimRevision:4,verifiedAt:"2026-10-02T10:10:00Z",verdict:"challenges"});const evidence=evidenceReadinessInput(l,"doc","C",4,[{basisId:"BASIS-R4",status:"VALID"}]);expect(evidence).toEqual([{id:"e1",status:"VALID"}]);const report=evaluateAcademicReadiness({graphIssues:[],coverage:[],evidence,protectedFacts:[],analysis:[],instructionIssues:[],lekta:{status:"clean",findingCount:0}});expect(report.findings.filter(x=>x.area==="evidence")).toEqual([]);});
 it("fails closed on conflicting canonical evaluation results for the same basis",()=>{let l=attachEvidenceReview({links:[],verifications:[]},link);l=verifyEvidenceReviewForRevision(l,{documentId:"doc",verificationId:"v4",linkId:"e1",basisId:"BASIS-R4",claimRevision:4,verifiedAt:"2026-10-02T10:10:00Z",verdict:"supports"});expect(evidenceReadinessInput(l,"doc","C",4,[{basisId:"BASIS-R4",status:"VALID"},{basisId:"BASIS-R4",status:"RECHECK_REQUIRED"}])).toEqual([{id:"e1",status:"RECHECK_REQUIRED"}]);});
 it("fails readiness closed when a reviewed basis snapshot has no canonical validity result",()=>{let l=attachEvidenceReview({links:[],verifications:[]},link);l=verifyEvidenceReviewForRevision(l,{documentId:"doc",verificationId:"v4",linkId:"e1",basisId:"BASIS-R4",claimRevision:4,verifiedAt:"2026-10-02T10:10:00Z",verdict:"supports"});expect(evidenceReadinessInput(l,"doc","C",4,[])).toEqual([{id:"e1",status:"RECHECK_REQUIRED"}]);});
 it("omits source links not yet attached at the historical revision",()=>{const l=attachEvidenceReview({links:[],verifications:[]},link);expect(evidenceReadinessInput(l,"doc","C",3,[])).toEqual([]);});
});
