import{describe,expect,it}from"vitest";import{attachEvidenceReviewToCurrentBinding,evidenceBasisReviewRef,evidenceVerificationForCurrentBinding,evidenceReviewLinkForCurrentBinding,verifyEvidenceReviewForCurrentBinding}from"./evidence-binding-adapter";
const binding={documentId:"doc",bindingId:"b5",objectId:"CLAIM-014",objectType:"claim"as const,objectRevision:5,nodeId:"n1",boundAt:"2026-10-02T11:00:00Z",bindingVersion:2,previousBindingId:"b4"};
const ref={basisId:"BASIS-R5",claimId:"CLAIM-014",sourceId:"SRC-1",nodeId:"n1"};
describe("EvidenceBasis current-binding review adapter",()=>{
 it("links a stable claim-source relationship to the exact current claim revision",()=>{const link=evidenceReviewLinkForCurrentBinding(binding,{linkId:"e1",sourceId:"SRC-1",attachedAt:"2026-10-02T11:01:00Z"});expect(link).toMatchObject({documentId:"doc",claimId:"CLAIM-014",sourceId:"SRC-1",attachedRevision:5});});
 it("derives a review ref from the existing canonical EvidenceBasis model",()=>{const basis={id:"B1",claim:{claimId:"CLAIM-014",documentRevision:7,target:{nodeId:"n1",quote:"tekst",prefix:"",suffix:"",startHint:0,endHint:5},text:"tekst"},source:{sourceId:"SRC-1",version:"v1",title:"Izvor",locatorLabel:"str. 1"},excerpt:{sourceId:"SRC-1",sourceVersion:"v1",locator:"str. 1",text:"navod",kind:"quote"},reviewedAt:"2026-10-02T11:00:00Z"} as never;expect(evidenceBasisReviewRef(basis)).toEqual({basisId:"B1",claimId:"CLAIM-014",sourceId:"SRC-1",nodeId:"n1"});});
 it("rejects source-link attachment before the current revision became effective",()=>expect(()=>attachEvidenceReviewToCurrentBinding({links:[],verifications:[]},binding,{linkId:"e1",sourceId:"SRC-1",attachedAt:"2026-10-02T10:59:59Z"})).toThrow("before current revision"));
 it("rechecks an older source link with a new EvidenceBasis snapshot for the current revision",()=>{let l=attachEvidenceReviewToCurrentBinding({links:[],verifications:[]},{...binding,objectRevision:4,boundAt:"2026-10-02T10:00:00Z",bindingId:"b4",bindingVersion:1,previousBindingId:null},{linkId:"e1",sourceId:"SRC-1",attachedAt:"2026-10-02T10:01:00Z"});expect(()=>evidenceVerificationForCurrentBinding(l,binding,{verificationId:"v5",linkId:"e1",basis:ref,verifiedAt:"2026-10-02T10:59:59Z",verdict:"supports"})).toThrow("before current revision");l=verifyEvidenceReviewForCurrentBinding(l,binding,{verificationId:"v5",linkId:"e1",basis:ref,verifiedAt:"2026-10-02T11:01:00Z",verdict:"supports"});expect(l.verifications[0]).toMatchObject({claimRevision:5,basisId:"BASIS-R5",verdict:"supports"});});
 it("rejects a basis snapshot belonging to another source claim or node",()=>{const l=attachEvidenceReviewToCurrentBinding({links:[],verifications:[]},binding,{linkId:"e1",sourceId:"SRC-1",attachedAt:"2026-10-02T11:01:00Z"});for(const bad of [{...ref,sourceId:"OTHER"},{...ref,claimId:"OTHER"},{...ref,nodeId:"other"}])expect(()=>evidenceVerificationForCurrentBinding(l,binding,{verificationId:crypto.randomUUID(),linkId:"e1",basis:bad,verifiedAt:"2026-10-02T11:02:00Z",verdict:"supports"})).toThrow("basis mismatch");});
 it("rejects non-claim bindings",()=>expect(()=>attachEvidenceReviewToCurrentBinding({links:[],verifications:[]},{...binding,objectType:"result" as const},{linkId:"e1",sourceId:"SRC-1",attachedAt:"2026-10-02T11:01:00Z"})).toThrow("not a claim"));
});
