import"fake-indexeddb/auto";import{afterEach,describe,expect,it}from"vitest";import Dexie from"dexie";import{appendEvidenceReviewLink,appendEvidenceReviewVerification,EVIDENCE_BASIS_DB_NAME,loadEvidenceReviewLedger,openEvidenceBasisStore}from"./evidence-basis-db";
afterEach(async()=>Dexie.delete(EVIDENCE_BASIS_DB_NAME));
const link={documentId:"doc",linkId:"e1",claimId:"C",sourceId:"S",attachedRevision:4,attachedAt:"2026-10-02T10:00:00Z"};
describe("EvidenceBasis review persistence",()=>{
 it("round-trips append-only revision-specific review history",async()=>{const o=await openEvidenceBasisStore();if(!o.ok)throw new Error("open");await appendEvidenceReviewLink(o.db,link);await appendEvidenceReviewVerification(o.db,{documentId:"doc",verificationId:"v4",linkId:"e1",basisId:"BASIS-R4",claimRevision:4,verifiedAt:"2026-10-02T10:10:00Z",verdict:"supports"});const r=await loadEvidenceReviewLedger(o.db);expect(r.ok).toBe(true);if(r.ok){expect(r.ledger.links).toEqual([link]);expect(r.ledger.verifications[0]).toMatchObject({basisId:"BASIS-R4"});}o.db.close();});
 it("enforces one persisted review verification per link/revision under concurrent writers",async()=>{const o=await openEvidenceBasisStore();if(!o.ok)throw new Error("open");await appendEvidenceReviewLink(o.db,link);const a=appendEvidenceReviewVerification(o.db,{documentId:"doc",verificationId:"a",linkId:"e1",basisId:"BASIS-A",claimRevision:4,verifiedAt:"2026-10-02T10:10:00Z",verdict:"supports"});const b=appendEvidenceReviewVerification(o.db,{documentId:"doc",verificationId:"b",linkId:"e1",basisId:"BASIS-B",claimRevision:4,verifiedAt:"2026-10-02T10:11:00Z",verdict:"challenges"});const rs=await Promise.allSettled([a,b]);expect(rs.filter(x=>x.status==="fulfilled")).toHaveLength(1);expect((await o.db.verifications.toArray())).toHaveLength(1);o.db.close();});
 it("preserves legacy unscoped review rows and fails closed",async()=>{const o=await openEvidenceBasisStore();if(!o.ok)throw new Error("open");await o.db.rows.add({id:"legacy",kind:"link",payload:{}});await expect(loadEvidenceReviewLedger(o.db)).resolves.toMatchObject({ok:false,reason:"invalid-ledger"});expect(await o.db.rows.get("legacy")).toBeDefined();o.db.close();});
 it("returns invalid-ledger for malformed typed rows rather than throwing",async()=>{const o=await openEvidenceBasisStore();if(!o.ok)throw new Error("open");await o.db.links.add({documentId:"doc",linkId:"bad"} as never);await expect(loadEvidenceReviewLedger(o.db)).resolves.toMatchObject({ok:false,reason:"invalid-ledger"});o.db.close();});
});
