import"fake-indexeddb/auto";import{afterEach,describe,expect,it}from"vitest";import Dexie from"dexie";import{appendReviewCoverage,loadReviewCoverage,openReviewCoverageStore,REVIEW_COVERAGE_DB_NAME}from"./review-coverage-db";
afterEach(async()=>Dexie.delete(REVIEW_COVERAGE_DB_NAME));
const row={documentId:"doc",bindingId:"b5",id:"r5",reviewerId:"mentor",objectId:"CLAIM-014",reviewedRevision:5,reviewedAt:"2026-10-02T11:05:00Z",status:"reviewed"as const};
describe("persistent document-scoped review coverage",()=>{
 it("round-trips immutable reviewer/revision history",async()=>{const o=await openReviewCoverageStore();if(!o.ok)throw new Error("open");await appendReviewCoverage(o.db,row);expect(await loadReviewCoverage(o.db)).toEqual({ok:true,rows:[row]});o.db.close();});
 it("keeps the same object id independent across documents",async()=>{const o=await openReviewCoverageStore();if(!o.ok)throw new Error("open");await appendReviewCoverage(o.db,row);await appendReviewCoverage(o.db,{...row,documentId:"other",id:"other"});const loaded=await loadReviewCoverage(o.db);expect(loaded.ok&&loaded.rows.map(x=>x.documentId)).toEqual(["doc","other"]);o.db.close();});
 it("rejects equal or older review timestamps for the same exact binding",async()=>{const o=await openReviewCoverageStore();if(!o.ok)throw new Error("open");await appendReviewCoverage(o.db,row);await expect(appendReviewCoverage(o.db,{...row,id:"same-time",status:"needs-work"})).rejects.toThrow("non-increasing time");await expect(appendReviewCoverage(o.db,{...row,id:"older",reviewedAt:"2026-10-02T11:04:59Z"})).rejects.toThrow("non-increasing time");o.db.close();});
 it("keeps an existing id immutable",async()=>{const o=await openReviewCoverageStore();if(!o.ok)throw new Error("open");await appendReviewCoverage(o.db,row);await expect(appendReviewCoverage(o.db,{...row,reviewedRevision:6})).rejects.toThrow("immutable");o.db.close();});
 it("refuses a new review write while legacy unscoped rows make the ledger invalid",async()=>{const o=await openReviewCoverageStore();if(!o.ok)throw new Error("open");await o.db.reviews.add({id:"legacy",reviewerId:"mentor",objectId:"C",reviewedRevision:4,reviewedAt:"2026-10-01T10:00:00Z",status:"reviewed"} as never);await expect(appendReviewCoverage(o.db,row)).rejects.toThrow("invalid-ledger");expect(await o.db.reviews.get("r5")).toBeUndefined();o.db.close();});
 it("preserves legacy unscoped rows but fails closed",async()=>{const o=await openReviewCoverageStore();if(!o.ok)throw new Error("open");await o.db.reviews.add({id:"legacy",reviewerId:"mentor",objectId:"C",reviewedRevision:4,reviewedAt:"2026-10-01T10:00:00Z",status:"reviewed"} as never);await expect(loadReviewCoverage(o.db)).resolves.toEqual({ok:false,reason:"invalid-ledger"});expect(await o.db.reviews.get("legacy")).toBeDefined();o.db.close();});
});
